#!/usr/bin/env bash
# Connects to server 35.153.57.116 with key in ~/.ssh/school

ssh ubuntu@35.153.57.116 -i ~/.ssh/school
#!/usr/bin/env bash
# Connects to server 35.153.57.116 with key in ~/.ssh/school


eval $("ssh-agent")

ssh add ~/.ssh/school


ssh ubuntu@35.153.57.116
